rooms:
  living_room: [living, living room, living-room]
  bedroom: [bedroom, bed room]
  lobby: [lobby, entrance hall]
  kitchen: [kitchen]
objects:
  apple: [apple]
  toy_penguin: [toy penguin, penguin]
  rabbit_doll: [rabbit doll]
  bear_doll: [bear doll, teddy bear]
  dog_doll: [dog doll]
  canned_juice: [canned juice, juice can]
  sugar: [sugar]
  soysauce: [soy sauce, soysauce]
  sauce: [sauce]
  ketchup: [ketchup]
  tumbler: [tumbler]
  white_cup: [white cup]
  pink_cup: [pink cup]
  empty_ketchup: [empty ketchup]
  filled_ketchup: [filled ketchup]
  ground_pepper: [ground pepper]
  salt: [salt]
  empty_plastic_bottle: [empty plastic bottle]
  filled_plastic_bottle: [filled plastic bottle]
  cubic_clock: [cubic clock, cube clock]
  toy_car: [toy car]
  toy_duck: [toy duck]
  nursing_bottle: [nursing bottle, baby bottle]
  cigarette: [cigarette]
  hourglass: [hourglass]
  camera: [camera]
  rubiks_cube: [rubik's cube, rubiks cube]
  spray_bottle: [spray bottle]
  matryoshka: [matryoshka, nesting doll]
  game_controller: [game controller]
  piggy_bank: [piggy bank]
destinations:
  avatar: [avatar, here, bring it to me, give it to me, person, human]
  white_side_table: [white side table]
  corner_sofa: [corner sofa]
  round_low_table: [round low table]
  square_low_table: [square low table]
  wooden_shelf: [wooden shelf]
  armchair: [armchair, arm chair]
  dining_table: [dining table]
  wooden_side_table: [wooden side table]
  wooden_bed: [wooden bed]
  iron_bed: [iron bed]
  wagon: [wagon, trolley]
  trash_box_for_recycle: [recycle trash box, recycling bin]
  trash_box_for_burnable: [burnable trash box, burnable bin]
  trash_box_for_bottle_can: [bottle can trash box, bottle and can bin]
  cardboard_box: [cardboard box]
