internal_name: Layout2021HM01
map: package://handyman_ros2/maps/2021HM01.yaml
initial_pose: {x: 0.0, y: 0.0, yaw: 0.0}
rooms:
  living_room:
    region: [[-2.5, -3.5], [5.0, -3.5], [5.0, 2.0], [-2.5, 2.0]]
    search_points:
      - {x: 1.0, y: 0.0, yaw: 0.0}
      - {x: 3.5, y: 0.0, yaw: 0.0}
  bedroom:
    region: [[0.0, -12.0], [5.0, -12.0], [5.0, -6.0], [0.0, -6.0]]
    search_points:
      - {x: 4.0, y: -8.5, yaw: 0.0}
      - {x: 1.69, y: -8.0, yaw: 0.0}
  lobby:
    region: [[-7.0, -11.5], [0.0, -11.5], [0.0, -3.5], [-7.0, -3.5]]
    search_points:
      - {x: -1.86, y: -8.38, yaw: 0.0}
      - {x: -4.86, y: -8.7, yaw: 0.0}
destinations:
  white_side_table:
    - {room: living_room, x: 2.15, y: 0.7, yaw: 1.57}
    - {room: bedroom, x: 1.3, y: -7.5, yaw: 1.57}
    - {room: lobby, x: -3.7, y: -10.3, yaw: -1.57}
  corner_sofa: [{room: lobby, x: -5.3, y: -10.2, yaw: -1.57}]
  armchair: [{room: bedroom, x: 4.0, y: -9.86, yaw: -1.57}]
  trash_box_for_burnable:
    - {room: living_room, x: -1.58, y: -1.05, yaw: 3.14}
    - {room: lobby, x: -3.17, y: -4.8, yaw: 1.57}
  dining_table:
    - {room: living_room, x: 1.5, y: -2.2, yaw: 0.0}
    - {room: lobby, x: -2.4, y: -8.4, yaw: 3.14}
  wooden_bed: [{room: bedroom, x: 1.8, y: -10.6, yaw: 3.14}]
  wooden_shelf: [{room: lobby, x: -4.13, y: -4.7, yaw: 1.57}]
  wagon:
    - {room: living_room, x: -1.6, y: -2.35, yaw: 3.14}
    - {room: bedroom, x: 0.27, y: -9.06, yaw: 0.0}
  cardboard_box: [{room: lobby, x: -6.2965, y: -6.9433, yaw: 3.14}]
